development:
  adapter: postgresql
  database: ddviqgmfg90oek
  host: ec2-23-23-225-50.compute-1.amazonaws.com
  username: eodghhsxchzmkz
  database: app-dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000